### ISSUE TITLE
Creating new tool section during installation

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/ansible-galaxy-tools#3]
It should be possible to also create new sections and put tools into multiple sections. @afgane do you know if the API supports this?

**Comment by natefoo** [comment]
Adding to this, it should also be possible to leave out the section entirely, for repositories that do not include tools (e.g. `package_*`).

**Comment by afgane** [comment]
@bgruening Creating new sections via the Galaxy API is not possible - the tool will just get installed outside any section: https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/api/tool_shed_repositories.py#L206
I couldn't think of a reason why this needs be like that so I think it's a matter of implementing it properly but I never got to it (clearly, nobody else has either).

@natefoo Not sure I get what you mean?

**Comment by natefoo** [comment]
@afgane I may occasionally want to install a repository that does not go in a section at all. Typically this is not the case, but it can happen (and was in fact my first test case for this role).

**Comment by gregvonkuster** [comment]
@bgruening @natefoo @afgane I believe creating a new tool panel section during an installation is now possible with this fix: https://github.com/galaxyproject/ansible-galaxy-tools/pull/34

**Comment by mvdbeek** [comment]
This should have long been closed with https://github.com/galaxyproject/ansible-galaxy-tools/pull/8/files ... I'm just curious why it has worked for me all along, while others seem to struggle.

**Comment by gregvonkuster** [comment]
@mvdbeek This PR https://github.com/galaxyproject/ansible-galaxy-tools/pull/8/files only allows for adding a tool to an existing section in the tool panel - just the same as using tool_panel_section_id.  The approach will not work with bioblend though, since the function signature does not accept a tool_panel_section_label.  This PR: https://github.com/galaxyproject/ansible-galaxy-tools/pull/34 allows for adding a new tool panel section label for the installation.  It uses the new_tool_panel_section_label param (which is supported by bioblend) rather than the tool_panel_section_label (which is not).

**Comment by mvdbeek** [comment]
Please see my comments on #34.
So what's going on here is that we have never used the kwargs of bioblend.
Now the version of bioblend adds one field, so indeed it's misaligned, but this has also been fixed in ephemeris.
